### ISSUE TITLE
Add team members to website (after filling out Stephan's form)

### ISSUE THREAD

**Issue by SoetkinB** [OpenMRBenelux/openmrbenelux.github.io#16]

**Comment by Remi-Gau** [comment]
For this we can maybe make a first merge of the "optimize-code" branch into master if you want.

That could help make things simpler.

I would still then keep the optimize code around because it will still be needed to make it easier to create a "program" page.

**Comment by DorienHuijser** [comment]
Yes I was also thinking that! I hope our merge won't result in much conflict though 😁

**Comment by Remi-Gau** [comment]
Am becoming an expert at this conflict resolution thing...

(only talking about code here... Nothing to do with solving major wars and I am still horrible in personal relationships... I commit too often and too early...)

...


Sent from my Samsung Galaxy smartphone.



-------- Original message --------
