### ISSUE TITLE
add a FAQ tab to menu

### ISSUE THREAD

**Issue by sofievdbos** [OpenMRBenelux/openmrbenelux.github.io#48]
Add a FAQ tab to the nav bar:

- What is a hackathon? > insert link to the 2021 hackathon repo
- Is OpenMR Virtual 2021 completely free of charge? > Yes, it sure is!
- ...

**Comment by DorienHuijser** [comment]
This is a great idea!!

- What is OpenMR?
- Who is OpenMR for?
- How do I propose a hackathon project? > This is something that was new to me last year and a bit confusing at the start (as in: what happens if you propose a project, who will join, what is expected of you)
- I have another question > Contact page or other low-level way to get in touch

**Comment by sofievdbos** [comment]
Great additional questions!! Do we create a Google Sheet to list all questions & answers? Then we can use the accordion system (cf. the one used for the bio on the team page) to create a FAQ tab in the nav bar. 😄

**Comment by DorienHuijser** [comment]
Ooh I don't know how that would work but that sounds awesome!! 
I feel another .yml file coming

**Comment by sofievdbos** [comment]
A bit like this, but replacing "Bio" by the question & putting the answer in the opening panel (first idea though).
Hello there `.yml`, here we come!! 😆 

https://user-images.githubusercontent.com/23309041/109959294-8f654380-7ce7-11eb-9300-270e2731dd58.mp4

**Comment by DorienHuijser** [comment]
See new document in drive: Website/FAQ_page_website 😄

**Comment by sofievdbos** [comment]
- I've committed a first version of the FAQ page to the [`faq` branch](https://github.com/OpenMRBenelux/openmrbenelux.github.io/tree/faq): [`3caab05`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/commit/3caab056de1ddf03c3dc8a10f9d3a09b8d0183db).
- I've version controlled the Google Sheet (`commit3caab05_faq-branch_210305`) to keep track: the content of that Google Sheet version is the same as the content of the `.yml` from this [`3caab05`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/commit/3caab056de1ddf03c3dc8a10f9d3a09b8d0183db) commit. 😃 We can then compare that Google Sheet version with a later version to see what should be changed in the `.yml`.

**Comment by DorienHuijser** [comment]
Sofie it looks AMAZING!!!! I made some small changes in the faq branch, so I also changed the Google doc + its version name :)

**Comment by Remi-Gau** [comment]
Just viewed the page locally. This is GREAT !!!!

Like you see falling in love with Jekyll's "liquid" programming and yaml. :-)

**Comment by sofievdbos** [comment]
After some additional tweaks, almost ready to be merged: PR #57!

**Comment by sofievdbos** [comment]
Comments from @Remi-Gau: 

- [x] Should we link to the Jupyter book definition of [hackathon](http://brainhack.org/brainhack_jupyter_book/glossary.html#unconference) + [unconference](http://brainhack.org/brainhack_jupyter_book/glossary.html#hackathon)? Me: Yes (as a source)! 😄 
- [x] Maybe we could link to the list of projects from the last Brainhack Global instead of [Brainhack Open Geneva 2020](https://brainhack.ch/#portfolio)? Me: Yes! 😄

**Comment by sofievdbos** [comment]
Comments were addressed on GH & adapted in Google Sheet; merging PR #57 = success! 🎉 
Closing this issue. 😄
