### ISSUE TITLE
create speaker yml + deploy page

### ISSUE THREAD

**Issue by sofievdbos** [OpenMRBenelux/openmrbenelux.github.io#52]

**Comment by sofievdbos** [comment]
info + bio + abstract

**Comment by sofievdbos** [comment]
Continuous deployment? See Slack thread.

**Comment by DorienHuijser** [comment]
I've started to update the speaker.yml with the 2021. It is not working yet (nor is it finished), but I cannot find the mistake :(

**Comment by sofievdbos** [comment]
**Update**: `speaker.yml` is working, to see all speaker-related commits up till now --> go to the [`speaker`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/tree/speakers) branch!

**Comment by sofievdbos** [comment]
- Day 1: Wednesday, 24 March 2021
  - [x] **Host**: Dorien Huijser
  - [x] Daniel Alcalá López
  - [x] Stefano Moia
  - [x] Melvin Selim Atay
  - [x] Felienne Hermans (except abstract -- panel)
  - [x] Jade Abbott (except abstract -- panel)
  - [x] Adora Nwodo (except abstract -- panel)
  - [x] Yo Yehudi
  - [x] Patrick Mineault (except abstract -- panel)
  - [x] Rémi Gau

- Day 2: Thursday, 25 March 2021
  - [x] **Host**: Sofie Van Den Bossche
  - [x] Stijn Denissen
  - [x] Rémi Gau
  - [x] Britta Westner (except abstract)

- Day 3: Friday, 26 March 2021
  - [x] **Host**: Stephan Heunis & Rémi Gau
  - [x] Sicco de Knecht
  - [x] Sarah Leuridan
  - [x] Simon Van Eyndhoven
  - [x] Gil Costa (only img)
  - [x] Stijn Denissen
  - [x] Kayla Green
  - [x] Guillaume Corradino
  - [x] Elodie Chabrol
  - [x] Veronika Cheplygina
  - [x] Moss Zhao

**Comment by sofievdbos** [comment]
I think the speaker page is ready for a merge. We can update the files whenever we receive new information! What do you think?

**Main technical changes > today**: 

- [`bd6f22f`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/commit/bd6f22f0725d42e88673a59652c44e134a8c36c4): I linked the speakers on the program page to their respective card/tile on the speaker page. 
- [`4c37488`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/commit/4c37488cf115332edcab10419563948cb14f250d): I rewrote the code to add the possibility for more abstracts per speaker, that is when you open the "abstract" accordion on the speaker page (usability: on day 3, some speakers have a talk + are member of the panel).

**Comment by sofievdbos** [comment]
🎊 PR #59 🎊

**Comment by DorienHuijser** [comment]
Only Sicco and Gil to go!

**Comment by sofievdbos** [comment]
And a general abstract for "Panel discussion: what constitutes clean, scientific code?" (day 1) & "Data visualization with MNE-Python" (Britta Westner, day 2), almost there!

**Comment by sofievdbos** [comment]
Note on the panel discussion abstracts:

- **Panel discussion: what constitutes clean, scientific code?** (day 1): Rémi & Yo Yehudi added an abstract of their own, therefore, I added a `-->  MY POINT OF VIEW  <--` to these abstracts on the speaker page. The general abstract can then be inserted above/under the personal ones annotated with `--> DISCUSSION TOPICS  <--` as I've done for the "Panel discussion: science communication" (day 3). 😄 
- **Panel discussion: science communication** (day 3): I annotated the general abstract with `--> DISCUSSION TOPICS  <--` (above the abstract txt).

If that sounds good, you can approve PR #60!

**Comment by DorienHuijser** [comment]
Now to do:
- [x] Abstract for panel day 1 @Remi-Gau could you provide a short one?
- [ ] Official abstract for Britta's talk (the one now was provided by Stijn)
- [x] Sicco
- [ ] Gil

**Comment by DorienHuijser** [comment]
Let's close this issue? :)

**Comment by sofievdbos** [comment]
Okidooooo! Closing now! 😄
