### ISSUE TITLE
create + embed form where interested "next year organizer" parties can sign up

### ISSUE THREAD

**Issue by sofievdbos** [OpenMRBenelux/openmrbenelux.github.io#55]
Could for example be linked to the astronauts on the team page (in the organizing committee & advisors section).

**Comment by DorienHuijser** [comment]
We should really do this. I'll put it on my to do to create a sign-up form this week

**Comment by DorienHuijser** [comment]
See: https://forms.gle/Fhxdv5yL8KD8vQSo9
Will embed this on a few locations on the website!

**Comment by DorienHuijser** [comment]
I have now linked to the form on the homepage and on the team page.
It is however not embedded anywhere yet, wasn't sure where. Ideas?

**Comment by sofievdbos** [comment]
Let's close this issue? 😄
