### ISSUE TITLE
create a Google calendar for our program -- automatically update times based on the user’s time zone

### ISSUE THREAD

**Issue by sofievdbos** [OpenMRBenelux/openmrbenelux.github.io#56]
example: https://brainhack-donostia.github.io/schedule/

**Comment by DorienHuijser** [comment]
May be a bit late for this to change it now?

**Comment by sofievdbos** [comment]
Jups! Although we do already have a Google Calendar & I know the added code line to automatically update times based on the user’s time zone when embedding it in a website. Might create a button on the program page which upon clicking goes to a separate website page (not shown in the nav) where they can see that Google Calendar thingy in their own time zones. I'll ping you if/when I wld manage that. But I agree, no high priority (compared to other things on our to do list)! 😁

**Comment by DorienHuijser** [comment]
Ahh cool! If it's not too much effort and you have time left somehow (ha-ha), that sounds good :D

**Comment by sofievdbos** [comment]
>> embedding conflicted with us wanting the links in Google Calendar to be private (embedding = public) => not implemented

Let's close this issue as well? 😄
