### ISSUE TITLE
Investigate and fix "mashed dates" on lading page (potentially an OS problem ????)

### ISSUE THREAD

**Issue by Remi-Gau** [OpenMRBenelux/openmrbenelux.github.io#58]

**Comment by sofievdbos** [comment]
It might be an svg rendering problem (svg was exported from pptx).

**Comment by Remi-Gau** [comment]
ooooooh

that would explain why I could not find the text of the date defined anywhere in any HTML file...

**Comment by sofievdbos** [comment]
We can (again 🤦 pptx + svg = 404 error 404 error 404 over and over againnnn -- why do they even provide it as an option 🤦) replace it by the png/jpg, although the quality is lower? Or do you know of any reliable png/jpg/whatever-to-svg converter -- just googled it: https://logosbynick.com/inkscape-convert-png-to-svg/, but seems troublesome. Directly starting over in Inkscape might be easier, but I'm gonna put it as a lower priority for now as there are some more urgent tasks to be completed. 😄

**Summary**: 
- [x] **intermediate solution**: replace svg by png/jpg
- [ ] **later**: create a more reliable svg

**Comment by Remi-Gau** [comment]
yeah a png should do the job.

**Comment by sofievdbos** [comment]
See [`a529c21`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/commit/a529c215e44778d8e248721cd4c90f26e583ad71) & [`1d994ac`](https://github.com/OpenMRBenelux/openmrbenelux.github.io/commit/1d994ac505c3952794386786f74531ba8597fc5d): I changed the logo format from svg to png. Works on Windows. Also 👍 for Linux?

**Comment by Remi-Gau** [comment]
closing old issues of mine
